repos:
  # --- Ruff: lint + format ---
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0  # pre-commit autoupdate to this version on 2024-06-19
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-yaml

  # - repo: https://github.com/pycqa/flake8
  #   rev: 7.1.1
  #   hooks:
  #     - id: flake8
